### ISSUE TITLE
php8動作確認と不具合修正

### ISSUE THREAD

**Issue by lowprice** [symfoware/cheetan#6]
こんにちは！
PHP8のシェルスクリプトのベースとして使いたかったので、
動作確認したのですが、$dataの変数が存在しないエラーが発生して動きませんでした。
多少のコード修正で対応できましたが、pull requestとかしても良いでしょうか？

php -S 192.168.1.3:8000 -t ~/works/cheetan-master/
http://192.168.1.3:8000/hello.php
または
php hello.php
で確認

**Comment by symfoware** [comment]
ご連絡ありがとうございます。
PHP 8に対応してみました。
